apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack-new
spec:
  eventBusName: codefresh-eventbus
  dependencies:
    - eventName: push-commit
      eventSourceName: push-commit
      name: push-commit
  triggers:
    - template:
        name: slack-trigger
        slack:
          sender:
            username: "Very Cool Robot"
            icon: ":robot_face:"
          channel: random
          message: "hello world"
#           blocks: |
#             [{
#             "type": "actions",
#             "block_id": "actionblock789",
#             "elements": [
#               {
#                 "type": "datepicker",
#                 "action_id": "datepicker123",
#                 "initial_date": "1990-04-28",
#                 "placeholder": {
#                   "type": "plain_text",
#                   "text": "Select a date"
#                 }
#               },
#               {
#                 "type": "overflow",
#                 "options": [
#                   {
#                     "text": {
#                       "type": "plain_text",
#                       "text": "*this is plain_text text*"
#                     },
#                     "value": "value-0"
#                   },
#                   {
#                     "text": {
#                       "type": "plain_text",
#                       "text": "*this is plain_text text*"
#                     },
#                     "value": "value-1"
#                   },
#                   {
#                     "text": {
#                       "type": "plain_text",
#                       "text": "*this is plain_text text*"
#                     },
#                     "value": "value-2"
#                   },
#                   {
#                     "text": {
#                       "type": "plain_text",
#                       "text": "*this is plain_text text*"
#                     },
#                     "value": "value-3"
#                   },
#                   {
#                     "text": {
#                       "type": "plain_text",
#                       "text": "*this is plain_text text*"
#                     },
#                     "value": "value-4"
#                   }
#                 ],
#                 "action_id": "overflow"
#               },
#               {
#                 "type": "button",
#                 "text": {
#                   "type": "plain_text",
#                   "text": "Click Me"
#                 },
#                 "value": "click_me_123",
#                 "action_id": "button"
#               }
#             ]
#             }]
          attachments: |
            [{
              "title": "New Slack Trigger Attachment1!",
              "title_link": "https://github.com/am-i-ok",
              "color": "#18be52",
              "fields": [{
                "title": "Hello1",
                "value": "Hello1 World1",
                "short": true
              }, {
                "title": "Hello2",
                "value": "Hello2 World2",
                "short": true
              }]
            }, {
              "title": "New Slack Trigger Attachment2!",
              "title_link": "https://github.com/am-i-ok",
              "color": "#18be52",
              "fields": [{
                "title": "Hello1",
                "value": "Hello1 World1",
                "short": true
              }, {
                "title": "Hello2",
                "value": "Hello2 World2",
                "short": true
              }]
            }]
          slackToken:
            key: token
            name: slack-secret
