apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack-new
spec:
  eventBusName: codefresh-eventbus
  dependencies:
    - eventName: push-commit
      eventSourceName: push-commit
      name: push-commit
  triggers:
    - template:
        name: slack-trigger
        slack:
          channel: random
          message: hello world
          attachments: |
            [{
              "title": "New Slack Trigger Attachment1!",
              "title_link": "https://github.com/am-i-ok",
              "color": "#18be52",
              "fields": [{
                "title": "Hello1",
                "value": "Hello1 World1",
                "short": true
              }, {
                "title": "Hello2",
                "value": "Hello2 World2",
                "short": true
              }]
            }, {
              "title": "New Slack Trigger Attachment2!",
              "title_link": "https://github.com/am-i-ok",
              "color": "#18be52",
              "fields": [{
                "title": "Hello1",
                "value": "Hello1 World1",
                "short": true
              }, {
                "title": "Hello2",
                "value": "Hello2 World2",
                "short": true
              }]
            }]
          slackToken:
            key: token
            name: slack-secret
