apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  dependencies:
    - eventName: push-commit
      eventSourceName: push-commit
      name: push-commit
  triggers:
    - template:
        name: slack-trigger
        slack:
          channel: test21
          message: hello world
          slackToken:
            key: token
            name: slack-secret
#       parameters:
#         - src:
#             dependencyName: test-dep
#             dataKey: body.message
#           dest: slack.message
